SMS.Web/Controllers/RecipeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using SMS.Data.Services;
using SMS.Web.ViewModels;
using SMS.Data.Models;
using SMS.Data.Security;

namespace SMS.Web.Controllers
{
    [Authorize]
    public class RecipeController : BaseController
    {
        private readonly IFoodService svc;

        public RecipeController(IFoodService ss)
        {
            svc = ss;
        } 


        // GET /recipe/index - 
        public IActionResult Index(RecipeSearchViewModel rm) //indivdual user recipe index
        {
            var userId = User.GetSignedInUserId();

            rm.Recipes = svc.SearchMyRecipes(rm.Range, userId, rm.Query);
            return View(rm);
        }

        // // GET /recipe/index - 
        public IActionResult RecipeIndex(RecipeSearchViewModel rm) //recipe list - recipeindex - all users recipes 
        {
                 
            rm.Recipes = svc.SearchAllRecipes(rm.Range, rm.Query);
            return View(rm);  
        }    

       

        // GET/recipe/{id}
        public IActionResult Details(int id)
        {
            var recipe = svc.GetRecipeById(id);
            if (recipe == null)
            {
                Alert("Recipe Not Found", AlertType.warning);  
                return RedirectToAction(nameof(Index));             
            }

            return View(recipe);
        }

        
        // GET /recipe/create
        [Authorize(Roles="member")]
        public IActionResult Create()
        {
            var userId = User.GetSignedInUserId();
            var recipe = new RecipeCreateViewModel {
                UserId = userId };

            return View(recipe);
        }
                
       
        // POST /recipe/create
        [HttpPost]
        [Authorize(Roles="member")]
        public IActionResult Create(RecipeCreateViewModel rvm)
        {
            if (ModelState.IsValid)
            {
                svc.CreateRecipe(rvm.UserId, rvm.Name, rvm.Diet, rvm.MealType, rvm.RecipeIngredients, rvm.Method, rvm.PrepTime, rvm.CookTime, rvm.Cuisine, rvm.Region, rvm.Translator, rvm.Calories, rvm.Servings, rvm.Price, rvm.PhotoUrl);// fix
     
                Alert($"Recipe created successfully for user {rvm.UserId}", AlertType.success); 
                return RedirectToAction(nameof(Index));
            }
            
            // redisplay the form for editing
            return View(rvm);
        }

        // GET /recipe/edit/{id}
        public IActionResult Edit(int id)
        {        
            // load the recipe using the service
            var r = svc.GetRecipeById(id);

            // check if r is null and if so alert
            if (r == null)
            {
                Alert($"Recipe {id} not found", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }   

            // pass recipe to view for editing
            return View(r);
        }

        // POST /recipe/edit/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles="admin, member")]
        public IActionResult Edit(Recipe r)
        {
            var recipe = svc.GetRecipeById(r.Id);
            
            // check if form is invalid and redisplay
            if (!ModelState.IsValid || recipe == null)
            {
                return View(r);
            } 

            // update user details and call service
            recipe.Name = r.Name;
            recipe.Diet = r.Diet;
            recipe.MealType = r.MealType;
            recipe.RecipeIngredients = r.RecipeIngredients;
            recipe.Method = r.Method;
            recipe.PrepTime = r.PrepTime;
            recipe.CookTime = r.CookTime;
            recipe.Cuisine = r.Cuisine;
            recipe.Region = r.Region;
            recipe.Translator = r.Translator;
            recipe.Calories = r.Calories;
            recipe.Servings = r.Servings;
            recipe.Price = r.Price;
            recipe.PhotoUrl = r.PhotoUrl;
       
            var updated = svc.UpdateRecipe(recipe);

            // check if error updating service
            if (updated == null) {
                Alert("There was a problem Updating. Please try again", AlertType.warning);
                return View(r);
            }

            
            Alert("Successfully Updated Recipe Details", AlertType.info);
            
            if (User.IsInRole("admin"))
                {
                    return RedirectToAction("RecipeIndex");
                }
                else
                {
                    return RedirectToAction("Index");
                }
            
        }

        // GET
        public IActionResult RecipeOwnerUserProfile(int id)
        {
            // retrieve the user with specifed id from the service
            var u = svc.GetUser(id);

            // Alert and redirection
            if (u == null)
            {
                Alert($"User not found", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }

            // pass user as parameter to the view
            return View(u);
        }

        // GET / recipe/delete/{id}
        [Authorize(Roles="admin, member")]      
        public IActionResult Delete(int id)
        {       
            // load the recipe using the service
            var r = svc.GetRecipeById(id);
            // check the returned recipe is not null and if so return NotFound()
            if (r == null)
            {
                // warning alert and redirect
                Alert($"Recipe {id} not found", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }     
            
            // pass recipe to view for deletion confirmation
            return View(r);
        }

        // POST /recipe/delete/{id}
        [HttpPost]
        [Authorize(Roles="admin, member")]
        [ValidateAntiForgeryToken]              
        public IActionResult DeleteConfirm(int id)
        {
            // delete recipe via service
            svc.DeleteRecipe(id);

            Alert("Recipe deleted successfully", AlertType.info);
            // redirect to the index view
            return RedirectToAction(nameof(Index));
        }

        // GET
        public IActionResult AddReview(int id)
        {
            var check = User.GetSignedInUserId();
            var r = svc.GetRecipeById(id);  
            if (r.Id == check)   
            {
                Alert($"You can not review your own recipes");
                return RedirectToAction(nameof(Index));
            }
                      
            if (r == null)
            {
                Alert($"Recipe not found", AlertType.warning);  
                return RedirectToAction(nameof(Index));
            }

            //Otherwise, a new review is created 
            var re = new ReviewViewModel 
            {      

                RecipeId = id,
                                
            };
            //render form
            return View("AddReview", re);  

        }

        // POST 
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult AddReview(Review r)
        {         
            var re = svc.GetRecipeById(r.RecipeId);        

            if (re == null)                             
            {   
                Alert($"Recipe not found", AlertType.warning);  
                return RedirectToAction(nameof(Index));
            }

            svc.AddReview(r);      
               
            Alert("Review added successfully", AlertType.success); 
            return RedirectToAction("Details", new { Id = r.RecipeId });
                     
        }

        public IActionResult EditReview(int id)
        {
            var check = User.GetSignedInUserId();
            var r = svc.GetReviewById(id);  
            if (r.Id == check)   
            {
                Alert($"You can not edit your own recipe reviews");
                return RedirectToAction(nameof(Index));
            }
                      
            if(r == null)
            {
                Alert($"Review not found", AlertType.warning);  
                return RedirectToAction(nameof(RecipeIndex));
            }

            //otherwise
            return View(r);

        }

        // POST /recipe/edit/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles="admin, member")]
        public IActionResult EditReview(Review r)
        {
            var review = svc.GetReviewById(r.Id);
            
            // check if form is invalid and redisplay
            if (!ModelState.IsValid || review == null)
            {
                return View(r);
            } 

            // update user details and call service
            review.Name = r.Name;
            review.ReviewedOn = r.ReviewedOn;
            review.Comment = r.Comment;
            review.Rating = r.Rating;
            
       
            var updated = svc.UpdateReview(review);

            // check if error updating service
            if (updated == null) {
                Alert("There was a problem Updating. Please try again", AlertType.warning);
                return View(r);
            }

            
            Alert("Successfully Updated Review Details", AlertType.info);
            
            if (User.IsInRole("admin"))
                {
                    return RedirectToAction("RecipeIndex");
                }
                else
                {
                    return RedirectToAction("Index");
                }
            
        }


       
        // GET 
        public IActionResult DeleteReview(int id)
        {

            var check = User.GetSignedInUserId();
            var r = svc.GetReviewById(id);  
            if (r.Id == check)   
            {

SMS.Web/Views/Shared/_Alert.cshtml
@{
    string message = (string)TempData["Alert.Message"];
    string type    = (string)TempData["Alert.Type"];
}

@if (message != null && type != null)
{
    <div class="alert alert-@type alert-dismissible fade show" role="alert" aria-label="@type">            
        @message
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>    
}

SMS.Web/Views/Shared/_AlertIcons.cshtml
@{
    string message = (string)TempData["Alert.Message"];
    string type    = (string)TempData["Alert.Type"];
}

<!-- svg icon definitions -->
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="icon-success" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="icon-info" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="icon-warning" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
  <symbol id="icon-danger" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>

<!-- only display alert if message and type are set -->
@if (message != null && type != null)
{
    <div class="alert alert-@type alert-dismissible fade show" role="alert">
        <div>
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="@type">
                <!-- select svg icon based on alert type -->       
                <use xlink:href="#icon-@type"/>   
            </svg>
            @message
        </div>
       
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>    
}

SMS.Web/Views/Shared/_BreadCrumbs.cshtml
<!-- model contains array of breadcrumb tuples (link,crumb) -->
@model IList<(string,string)>

@if (Model != null ) {
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      @foreach(var (link,crumb) in Model)
      {
          @if (link == null || link.Length == 0)
          {
              <li class="breadcrumb-item active" aria-current="page">@crumb</li>
          }
          else
          {
              <li class="breadcrumb-item"><a href="@link">@crumb</a></li>
          }
      }
    </ol>
  </nav>
}

SMS.Web/Views/Shared/_DeleteRecipeModal.cshtml
@model Recipe

<!-- Delete Modal -->
<div id="deleteRecipeModal" class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="navbar-title modal-title">Delete Recipe</h5>
            </div>
            
            <div class="modal-body text-center">
                <p>Are you sure you want to delete this Recipe?</p>
                <p><b>This action can not be undone</b></p>
            </div>

            <div class="col card rounded shadow p-3">
                <dl class="row">       
                    <dt class="col-5">Recipe Name</dt>
                    <dd class="col-7">@Model.Name</dd>

                    <dt class="col-5">Cuisine</dt>
                    <dd class="col-7">@Model.Cuisine</dd>

                    <dt class="col-5">Translation</dt>
                    <dd class="col-7">@Model.Translator</dd> 
                    
                    <dt class="col-5">Rating</dt>
                    <dd class="col-7">@Model.Rating%</dd>        
                </dl>
            </div>

            <div class="modal-footer">
                <form asp-controller="User" asp-action="RecipeDeleteConfirm" type="post">
                    <input type="hidden" asp-for="Id" />
                    <input type="hidden" asp-for="UserId"/>

                    <input type="submit" value="Confirm" class="btn btn-danger" />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                </form>
            </div>
        </div>
   

SMS.Web/Views/Shared/_DeleteUserModal.cshtml
@model User

<!-- Delete Modal -->
<div id="deleteUserModal" class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="navbar-title modal-title">Delete User</h5>
            </div>
            <div class="modal-body text-center">
                <p>Are you sure you want to delete this user?</p>
                <p><b>This action can not be undone</b></p>
            </div>

            <div>
                <div class="col card rounded shadow p-3">
                    <dl class="row">       
                        <dt class="col-5">Name</dt>
                        <dd class="col-7">@Model.Name</dd>

                        <dt class="col-5">Email</dt>
                        <dd class="col-7">@Model.Email</dd>
                        
                        <dt class="col-5">Role</dt>
                        <dd class="col-7">@Model.Role</dd>
                    </dl>
                </div>  
            </div>

            <div class="modal-footer">
                <form asp-action="DeleteConfirm" type="post">
                    <input type="hidden" asp-for="Id" />
                    <input type="submit" value="Confirm" class="btn btn-danger" />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>

SMS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SMS.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SMS.Web.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="css/site.css" >
    <style>
        .navbar-custom 
        {
            background-color: #2C8C7E;
        }

        .navbar
        {
            background-color: #ffffff

        }

        .navbar-title
        {
            font-family: Segoe Script;
            color: #ff4500
        }


        .btn-outline,
        .btn-outline:hover {
        border-color: currentcolor;
        }

        .btn-outline {
        border-radius: var(--border-radius);
        }

    </style>
</head>
<body>
    <header>
      <nav class="navbar navbar-expand-sm mb-3">
            <div class="container-fluid">
                <a class="navbar-brand navbar-title bi bi-globe2" asp-area="" asp-controller="Home" asp-action="Index"><b> The Good Food Atlas</b></a>
                <button type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu" class="navbar-toggler"><span class='navbar-toggler-icon'></span></button>
                    <span class="navbar-toggler-icon"></span>
                </button>    
                         
                <!-- Home Page in Nav bar -->         
                <div class='collapse navbar-collapse d-flex justify-content-between' id='navbar-menu'>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                         <!-- Members/Admin Own Profile in Nav bar -->
                        <li class="nav-item">
                            <a asp-condition=@(User.HasOneOfRoles("admin,member")) class="nav-link text-dark" asp-controller="User" asp-action="UserProfile"> My Profile</a>
                        </li> 

                        <!-- Users in nav bar for Admin -->                       
                       <li class="nav-item">
                            <a asp-condition =@(User.IsInRole("admin")) class="nav-link text-dark" asp-controller="User" asp-action="Index"> Users</a>
                        </li> 


                        <!-- Members Own Recipes in Nav bar -->
                        <li class="nav-item">
                            <a asp-condition =@(User.IsInRole("member")) class="nav-link text-dark" asp-controller="Recipe" asp-action="Index"> My Recipes</a>
                        </li> 

                        <!-- All Recipes on Web Application from all members -->
                        <li class="nav-item">
                            <a asp-condition=@(User.HasOneOfRoles("admin,member")) class="nav-link text-dark" asp-controller="Recipe" asp-action="RecipeIndex">All Recipes</a>
                        </li> 
                        
                        <!-- Company Dropdown -->
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" data-bs-toggle="dropdown" href="#" 
                               role="button" aria-expanded="false">Company</a>
                            <ul class="dropdown-menu">
                                <li> <a class="dropdown-item bi bi-building" asp-controller="Home" asp-action="About"> About Us</a></li>
                                <li> <a class="dropdown-item bi bi-shield-fill-exclamation" asp-controller="Home" asp-action="Privacy"> Our Privacy</a></li>
                                <li> <a class="dropdown-item bi bi-person-lines-fill" asp-controller="Home" asp-action="Contact"> Contact Us</a></li>
                            </ul>
                    </ul>
                    
                    <!-- Login/Register nav items -->
                        <partial name="_Login" />

                </div>
            </div>
        </nav>
    </header>
        <div class="container">
            <!-- render the alert partial -->
            <partial name="_AlertIcons" />

            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - The Good Food Atlas- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>
</html>


SMS.Web/Views/Shared/_Login.cshtml
<!-- Login partial to display links on nav bar -->
<!-- Logged in -->
<div class="navbar-nav" asp-condition="@User.Identity.IsAuthenticated">  
    <div class="nav-item text-dark dropdown">
        <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi-person-circle"></i> @User.Identity.Name
        </a>
        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" asp-controller="User" asp-action="EditProfile"><i class="bi bi-gear"></i> Update Profile</a>
            <a class="dropdown-item" asp-controller="User" asp-action="UpdatePassword"><i class="bi bi-lock-fill"></i> Update Password</a>
            <hr class="dropdown-divider">
            <form asp-controller="User" asp-action="Logout">
                <button type="submit" class="dropdown-item btn btn-link text-dark"><i class="bi bi-door-open"></i> Logout</button>
            </form>
        </div>
    </div>         
</div>

<!-- Not Logged in -->
<div class="navbar-nav" asp-condition="@(!User.Identity.IsAuthenticated)">
    <a class="nav-link text-dark bi bi-box-arrow-in-right"  asp-controller="User" asp-action="Login"> Login</a>
    <a class="nav-link text-dark bi bi-person-plus"  asp-controller="User" asp-action="Register"> Register</a>
</div>






SMS.Web/Views/Shared/_Recipes.cshtml
<!-- Recipe partial to display Recipes Details-->
@model User

@if (Model.Recipes.Count == 0)
{
    <h5>No Recipes</h5>
}
else
{
    <div class="card rounded shadow">
        <table class="table table-sm">
            <thead>
                <tr>           
                    <th>Name</th>
                    <th>Diet</th>  
                    <th>Cuisine</th>
                    <th>Calories</th>
                    <th>Servings</th>       
                    <th></th>  
                </tr>
            </thead>
            <tbody>
                @foreach(var r in Model.Recipes) {
                    <tr>              
                        <td>@r.Name</td>
                        <td>@r.Diet</td>  
                        <td>@r.Cuisine</td>  
                        <td>@r.Calories</td>  
                        <td>@r.Servings</td>  
                                                
                        <td>
                            <a title= "Recipe Details" asp-controller="Recipe" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-sm btn-danger"><i class="bi bi-info"></i></a>
                            <a asp-condition=@(User.IsInRole("admin")) asp-action="Edit" title="Edit Recipe" asp-route-id="@r.Id" class="btn btn-sm btn-danger"><i class="bi bi-pen"></i></a>
                            <a asp-condition=@(User.IsInRole("admin")) asp-action="RecipeDelete" title="Delete Recipe" asp-route-id="@r.Id" class="btn btn-sm btn-danger"><i class="bi bi-trash"></i></a>
                        </td>             
                    </tr>   
                }
            </tbody>
        </table>
    </div>
}

SMS.Web/Views/Shared/_Review.cshtml
<!-- Review partial to reduce code in Recipe Details Page -->
@if (Model.Reviews.Count == 0)
{
    <h4>This Recipe has yet to recieve any reviews</h4>
    
}
else
{

<div>
    <h3 class="mt-4 navbar-title"> Recipe Reviews </h3>
    <a asp-condition =@(User.IsInRole("member")) asp-controller="Recipe" asp-action="AddReview" asp-route-id="@Model.Id" class="btn btn-sm btn-danger mt-1 mb-2"> Add Review <i class="bi bi-pen ml-2"></i></a>
</div>


<table class="table table-sm table-striped table-bordered table-hover">
    <thead class="thead-dark">
        <tr>
            <th>Reviewed On</th>
            <th>Name</th>
            <th>Comment</th>
            <th>Recipe Rating 1 - 10<i class="bi bi-star-fill bi bi-star ml-2"></i></th>
            <th><i class="bi bi-trash ml-2"><th>
        </tr>
    </thead>
    <tbody>
        @foreach(var r in Model.Reviews)
        {
            <tr>
                <td>@r.ReviewedOn.ToString("MM/dd/yy H:mm")</td>
                <td>@r.Name</td>
                <td>@r.Comment</td>
                <td>@r.Rating</td>
                <td><a asp-controller="Recipe" asp-action="DeleteReview" asp-route-id="@Model.Id" class="btn btn-sm btn-light mr-4">Delete</a></td>
                
            </tr>    
        }
    </tbody>    
</table>  
}

SMS.Web/Views/Shared/_Weather.cshtml
<!-- Weather partial containing weather widget for Home Page -->

<a class="weatherwidget-io" href="https://forecast7.com/en/51d51n0d13/london/" data-label_1="LONDON" data-label_2="WEATHER" data-days="3" data-theme="original" data-basecolor="#0d8928" >LONDON WEATHER</a>
<script>
!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://weatherwidget.io/js/widget.min.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','weatherwidget-io-js');
</script>

SMS.Web/Views/Shared/_google.cshtml
<div id="google_translate_element"></div>
     <script src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
     <script>
      function googleTranslateElementInit(){
        new google.translate.TranslateElement(
          {
          pageLanguage: 'en'},
          'google_translate_element'
        );
      }
     </script>

     